spring:
  rabbitmq:
    host: 43.143.148.254
    port: 5672
    username: admin
    password: 123
  #解决配置swagger报错
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: 8080
  servlet:
    context-path: /api
